# IntelliJ Platform Artifacts Repositories
pluginGroup = com.github.sudohackin.bootyaml
pluginName = Spring Boot YAML Autocomplete
pluginRepositoryUrl = https://github.com/sudoHackIn/boot-yaml-plugin
pluginVersion = 1.0.0

# Gradle Releases
gradleVersion = 8.5

# Kotlin
kotlinVersion = 1.9.21

# IntelliJ Platform Properties
platformType = IC
platformVersion = 2023.2.5
